### ISSUE TITLE
Resurrected my miner 3 times already

### ISSUE THREAD

**Issue by sur1v** [aidanmelen/bobcat-miner-python#36]
Hello, just wanted to say thanks for sharing your tool. Is now in crontab, keep its running nicely in a screen session. Below a report of a unknown error reported by this recently deployed miner, maybe you have a clue. Thanks again!

```
# bobcat --ip-address 192.168.7.7 -C DEBUG autopilot
🐛 Connected to Bobcat: 192.168.1.7
🐛 The Bobcat Autopilot is starting 🚀 🚀 🚀
🐛 Lock Acquired: .bobcat.lock
🐛 Refresh: Miner Data
🐛 Refresh: Miner Data
🐛 Refresh: Status Data
❌ Online Status: Offline
🐛 Checking: Down or Error Status
🐛 Checking: Height API Error Status
🐛 Checking: Unknown Error Status
❌ Bobcat Status: Unknown
⚠️ Rebooting Bobcat
🐛 {"message":"rate limit exceeded"}
🐛 Waiting for 5 Minutes ⏳
🐛 Refresh: Status Data
🐛 Refresh: Miner Data
🐛 Refresh: Miner Data
✅ Reconnected to the Bobcat (spare-merlot-cougar)
🐛 Refresh: Status Data
🐛 Refresh: Miner Data
🐛 Refresh: Miner Data
⚠️ Resetting Bobcat
1: Your miner is going to rest
3: Housekeeper was sent home
3: Docker is going to be stopped
4: Boom! Old blockchain data gone
, exit status 1
6: Housekeeper is back, but everything is gone
7: Rebuilding everything
8: Cleaning up
Bam! Miner successfully restarted, but it may take 30 minutes to load files from internet. Please be patient. 2022-03-31 23:12:55 +0000 UTC
🐛 Waiting for 5 Minutes ⏳
🐛 Refresh: Status Data
🐛 Refresh: Miner Data
🐛 Refresh: Miner Data
⚠️ The Bobcat (spare-merlot-cougar) is not running
🐛 Waiting for 5 Minutes ⏳
```

**Comment by aidanmelen** [comment]
Another useful debug option is `--trace`. That will output the endpoint data returned by the bobcat (think miner.json from bobcat dashboard). For example:

```
$ bobcat --ip-address 192.168.7.7 -C DEBUG --trace autopilot
```

The response data might tell us more about what is going on.

**Comment by aidanmelen** [comment]
> this recently deployed miner

Has the bobcat been onboarded? That is a specific process that is outside the scope of this project. Since my bobcat was transferred to me; I never had a chance to reliably test that workflow.

**Comment by sur1v** [comment]
> Another useful debug option is `--trace`. That will output the endpoint data returned by the bobcat (think miner.json from bobcat dashboard). For example:
> 
> ```
> $ bobcat --ip-address 192.168.7.7 -C DEBUG --trace autopilot
> ```
> 
> The response data might tell us more about what is going on.

Thanks, I'll add it on my next runs



> > this recently deployed miner
> 
> Has the bobcat been onboarded? That is a specific process that is outside the scope of this project. Since my bobcat was transferred to me; I never had a chance to reliably test that workflow.

Yes, is all green now

**Comment by aidanmelen** [comment]
you might also find the [`--dry-run`](https://github.com/aidanmelen/bobcat-miner-python#dry-run) option useful.

**Comment by aidanmelen** [comment]
> Yes, is all green now

Did your issue get resolved?

**Comment by sur1v** [comment]
Hey, yes there was no issue, just wanted to report this error that looks like is not identified by the script, anyway still works and fix it. Thanks again!
