### ISSUE TITLE
Factory Reset

### ISSUE THREAD

**Issue by zak53** [aidanmelen/bobcat-miner-python#37]
Hello,

Is there an option to do a factory reset? I lost my 12 seeds, it's only been 6 months that I have this miner

Thank you

**Comment by aidanmelen** [comment]
> Hello,
> 
> 
> 
> Is there an option to do a factory reset? I lost my 12 seeds, it's only been 6 months that I have this miner
> 
> 
> 
> Thank you 

I am sure there is, but that is out of the scope of this tool. Best of luck!

**Comment by zak53** [comment]
Thanks for the fast replay, gonna keep searching mybee one day 🙂
